#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#       (1) You need a POSIX-compliant shell to run this script. If your /bin/sh does not
#           implement the POSIX standard, then try a different shell, like /bin/bash or /bin/dash.
#       (2) This script targets any POSIX shell, so it avoids extensions provided by
#           Bash or Ksh.
#       (3) If you need to pass special arguments to the JVM, you can use the
#           JAVA_OPTS or GRADLE_OPTS variables.
#       (4) The JVM must have a main method named "org.gradle.wrapper.GradleWrapperMain".
#           This script will set up the classpath for you.
#
##############################################################################

# Attempt to set APP_HOME
# Resolve links: $0 may be a link
PRG="$0"
# Need this for relative symlinks.
while [ -h "$PRG" ] ; do
    ls=`ls -ld "$PRG"`
    link=`expr "$ls" : '.*-> \(.*\)$'`
    if expr "$link" : '/.*' > /dev/null; then
        PRG="$link"
    else
        PRG=`dirname "$PRG"`"/$link"
    fi
done
SAVED="`pwd`"
cd "`dirname \"$PRG\"`/" >/dev/null
APP_HOME="`pwd -P`"
cd "$SAVED" >/dev/null

APP_NAME="Gradle"
APP_BASE_NAME=`basename "$0"`

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD="maximum"

warn () {
    echo "$*"
}

die () {
    echo
    echo "$*"
    echo
    exit 1
}

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false
case "`uname`" in
  CYGWIN* )
    cygwin=true
    ;;
  Darwin* )
    darwin=true
    ;;
  MINGW* )
    msys=true
    ;;
  NONSTOP* )
    nonstop=true
    ;;
esac

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD="$JAVA_HOME/jre/sh/java"
    else
        JAVACMD="$JAVA_HOME/bin/java"
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD="java"
    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
fi

# Increase the maximum file descriptors if we can.
if [ "$cygwin" = "false" -a "$darwin" = "false" -a "$nonstop" = "false" ] ; then
    MAX_FD_LIMIT=`ulimit -H -n`
    if [ $? -eq 0 ] ; then
        if [ "$MAX_FD" = "maximum" -o "$MAX_FD" = "max" ] ; then
            MAX_FD="$MAX_FD_LIMIT"
        fi
        ulimit -n $MAX_FD
        if [ $? -ne 0 ] ; then
            warn "Could not set maximum file descriptor limit: $MAX_FD"
        fi
    else
        warn "Could not query maximum file descriptor limit: $MAX_FD_LIMIT"
    fi
fi

# For Darwin, add options to specify how the application appears in the dock
if $darwin; then
    GRADLE_OPTS="$GRADLE_OPTS \"-Xdock:name=$APP_NAME\" \"-Xdock:icon=$APP_HOME/media/gradle.icns\""
fi

# For Cygwin or MSYS, switch paths to Windows format before running java
if [ "$cygwin" = "true" -o "$msys" = "true" ] ; then
    APP_HOME=`cygpath --path --mixed "$APP_HOME"`
    CLASSPATH=`cygpath --path --mixed "$CLASSPATH"`
    JAVACMD=`cygpath --unix "$JAVACMD"`

    # We build the pattern for arguments to be converted via cygpath
    ROOTDIRSRAW=`find -L / -maxdepth 1 -mindepth 1 -type d 2>/dev/null`
    SEP=""
    for dir in $ROOTDIRSRAW ; do
        ROOTDIRS="$ROOTDIRS$SEP$dir"
        SEP="|"
    done
    OURCYGPATTERN="(^($ROOTDIRS))"
    # Add a user-defined pattern to the cygpath arguments
    if [ "$GRADLE_CYGPATTERN" != "" ] ; then
        OURCYGPATTERN="$OURCYGPATTERN|($GRADLE_CYGPATTERN)"
    fi
    # Now convert the arguments - kudos to Bart Massey
    i=0
    for arg in "$@" ; do
        CHECK=`echo "$arg"|egrep -c "$OURCYGPATTERN" -`
        CHECK2=`echo "$arg"|egrep -c "^-"`
        if [ $CHECK -eq 1 ] && [ $CHECK2 -eq 0 ] ; then
            eval `printf ARGS[%d]="%s" "$i" "$(cygpath --path --ignore --mixed "$arg")"`
        else
            eval `printf ARGS[%d]="%s" "$i" "$arg"`
        fi
        i=`expr $i + 1`
    done
    # Fix the arguments
    set -- "${ARGS[@]}"
fi

# Split up the JVM_OPTS And GRADLE_OPTS into an array,
# to prevent over-eager splitting
JVM_OPTS=$(
    echo " "$JAVA_OPTS" "$GRADLE_OPTS" " |
    sed -e 's/[  ]*$//' |
    sed -e 's/^[  ]*//' |
    tr -s ' '
)
# Now fix quotes in JVM_OPTS, and make an array of tokens
# Note: this is not a general solution, and handles only the most common use case
eval JVM_ARGS='('"$JVM_OPTS"')'

# Extract the maximum heap size from -Xmx options
for option in "${JVM_ARGS[@]}" ; do
    if [ "${option:0:4}" = "-Xmx" ] ; then
        JVM_MAX_HEAP_SIZE="${option:4}"
    fi
done

# Setup the classpath
if [ "$cygwin" = "true" -o "$msys" = "true" ] ; then
    CLASSPATH_SEPARATOR=";"
else
    CLASSPATH_SEPARATOR=":"
fi

# Determine whether we need a console
if $cygwin || $msys ; then
    # We're on Windows. Use cmd /c to start a separate console.
    # This is needed because the command "start" in cygwin/msys
    # doesn't work properly.
    JAVACMD="$JAVACMD $JVM_OPTS -classpath \"$CLASSPATH\" org.gradle.wrapper.GradleWrapperMain $APP_ARGS"
    if [ -n "$GRADLE_HOME" ] ; then
        if [ "$cygwin" = "true" ] ; then
            GRADLE_HOME=`cygpath --mixed "$GRADLE_HOME"`
        fi
        JAVACMD="$JAVACMD -Dgradle.home=\"$GRADLE_HOME\""
    fi
    JAVACMD="$JAVACMD \"$@\""

    # When running in a mintty terminal (msys2), the above won't work
    # because mintty doesn't use the normal Windows console.
    # We'll just assume mintty is not in use for now.
    JAVACMD=`echo "$JAVACMD" | sed -e 's/\\\\/\\\\\\\\/g'`
    JAVACMD=`echo "$JAVACMD" | sed -e 's/"/\\"/g'`
    if [ "$cygwin" = "true" ] ; then
        JAVACMD=`cygpath --unix "$JAVACMD"`
    fi
    eval "$JAVACMD"
else
    # Normal OS X and Linux support
    exec "$JAVACMD" "${JVM_ARGS[@]}" -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"
fi
